

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: http://localhost:8082
          predicates:  
            - Path=/api/customers/**
        - id: product-service
          uri: http://localhost:8081
          predicates:  
            - Path=/api/products/**
        - id: shopping-service
          uri: http://localhost:8083
          predicates:  
            - Path=/api/invoices/**          
