

server:
  port: 8081
  error:
    include-message: always

spring:
   application:
     name: product-service

  ##=================================
  ##     Data base config
  ##=================================
   datasource:
     url: jdbc:postgresql://34.125.235.37/proyectdev
     username: martinv
     password: admin

  ##=================================
  ##     Hibernate Jpa config
  ##=================================

   jpa:
     database-platform: org.hibernate.dialect.PostgreSQLDialect
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
         show_sql: true
         format_sql: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  ##=================================
  ##     Eureka client config
  ##=================================    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/

  ##=================================
  ##     Actuator config
  ##=================================

management:
  health:
    circuitBreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  enpoint:
    health: 
      show-details: always   
