

server:
  port: 8083
  error:
    include-message: always

spring:
   application:
     name: shopping-service
  ##=================================
  ##  Client for admin server config
  ##=================================
    boot:
      admin:
        client:
          url: http://localhost:8088   

  ##=================================
  ##     Data base config
  ##=================================
   datasource:
     url: jdbc:postgresql://34.125.235.37/proyectdev
     username: martinv
     password: admin

  ##=================================
  ##     Hibernate Jpa config
  ##=================================

   jpa:
     database-platform: org.hibernate.dialect.PostgreSQLDialect
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
         show_sql: true
         format_sql: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/

  ##=================================
  ##     Rescilence4j config
  ##=================================

management:
  health:
    circuitBreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  enpoint:
    health: 
      show-details: always          

resilence4j:
  circuitbreaker:
    instances:
      customer-service:
        resilenceHealthIndicator: true
        eventCustomerBufferSize: 10
        faliureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHafOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      product-service:
        resilenceHealthIndicator: true
        eventCustomerBufferSize: 10
        faliureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHafOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED  
